const img1 = 'https://plus.unsplash.com/premium_photo-1661876449499-26de7959878f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60';
const img2 = 'https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60';
const img3 = 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60';
const FacilitiesList = [{
    iconType: 'Ionicons',
    icon: "ios-water-outline",
    name: 'Water',
    selected: true,
},
{
    iconType: 'MaterialCommunityIcons',
    icon: "gas-cylinder",
    name: 'Gas',
    selected: true,
},
{
    iconType: 'MaterialIcons',
    icon: "electrical-services",
    name: 'Electricity',
    selected: false,
},
{
    iconType: 'Ionicons',
    icon: "bus",
    name: 'Transport',
    selected: true,
},]
export const Data = [
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
    {
        region: 'ABC',
        district: 'XYZ',
        type: 'A',
        rooms: '6',
        kitchen: '2',
        toilets: '2',
        monthlyRent: '500',
        monthlyUpfront: '50',
        description: 'This is a beuutiful home at a reasonable price',
        deposit: '100',
        balcony: 'No',
        image: [img1, img2, img3],
        facilities: FacilitiesList,
        contact: '123456789'
    },
];

export const images = [{
    region: 'ABC',
    district: 'XYZ',
    type: 'A',
    rooms: '6',
    kitchen: '2',
    toilets: '2',
    monthlyRent: '500',
    monthlyUpfront: '50',
    description: 'This is a beuutiful home at a reasonable price',
    deposit: '100',
    balcony: 'No',
    image: [img1, img2, img3],
    facilities: FacilitiesList,
    contact: '123456789',
    rating: '4.9'
},
{
    region: 'ABC',
    district: 'XYZ',
    type: 'A',
    rooms: '6',
    kitchen: '2',
    toilets: '2',
    monthlyRent: '500',
    monthlyUpfront: '50',
    description: 'This is a beuutiful home at a reasonable price',
    deposit: '100',
    balcony: 'No',
    image: [img1, img2, img3],
    facilities: FacilitiesList,
    contact: '123456789',
    rating: '4.9'
}, {
    region: 'ABC',
    district: 'XYZ',
    type: 'A',
    rooms: '6',
    kitchen: '2',
    toilets: '2',
    monthlyRent: '500',
    monthlyUpfront: '50',
    description: 'This is a beuutiful home at a reasonable price',
    deposit: '100',
    balcony: 'No',
    image: [img1, img2, img3],
    facilities: FacilitiesList,
    contact: '123456789',
    rating: '4.9'
}, {
    region: 'ABC',
    district: 'XYZ',
    type: 'A',
    rooms: '6',
    kitchen: '2',
    toilets: '2',
    monthlyRent: '500',
    monthlyUpfront: '50',
    description: 'This is a beuutiful home at a reasonable price',
    deposit: '100',
    balcony: 'No',
    image: [img1, img2, img3],
    facilities: FacilitiesList,
    contact: '123456789',
    rating: '4.9'
},]
